### PR TITLE
no

### PR DESCRIPTION
**Pull request by ahldr**

### CODE REVIEW

**Comment by trickeydan** [comment]
@mildlyincompetent Please review

**Comment by mildlyincompetent** [comment]
thank you for your submission, this looks like a definite improvement to the code base, i shall see if i can get this cleared with the Dysfunctionals Blue Sky Thinking and Code Devouring Squad

**Review by kierdavis — APPROVED** [review]

**Comment by ahldr** [comment]
Excellent, could we sit down and whiteboard this? I'd like a clear go-to-market strategy applying this kind of cutting edge technology

**Comment by trickeydan** [comment]
I'll need to run this past our business synergy development management team leader's assistant first.

**Pull request closed without merging**
